
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module fpa_v3(

	//////////// CLOCK //////////
	input 		          		MAX10_CLK1_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// Arduino //////////
	inout 		     [1:0]		ARDUINO_IO,

	//////////// GPIO //////////
	inout 		     [7:0]		GPIO
);

	wire 				en, scan; //Enable signal for floating point addition and scan signal for keypad presses
	wire 				b0p, b1p; //Debounced button 0 and button 1 presses
	wire 				dn; //FP calc is finished
	wire 	[3:0]		curr_hex; //Current hex number being pressed by the keypad
	wire 	[15:0] 	result; //Result of floating point addition
	wire 	[15:0] 	in1, in2; //Inputs that will be added
	
	
	/// Submodule Instantiations ///
	keypad 			kp 	(.clk(MAX10_CLK1_50), .rst(b0p), .scan(scan), .data_in(GPIO[7:0]), .data(curr_hex));
	fpa 				add 	(.clk(MAX10_CLK1_50), .in1(in1), .in2(in2), .enable(en), .done(dn), .sum(result));
	seg_controller seg 	(.clk(MAX10_CLK1_50), .rst(b0p), .numb(curr_hex), .press(b1p), .out_st(ARDUINO_IO[1:0]), .in1(in1), .in2(in2), 
									.result(result), .en(en), .scan(scan), .Hex5(HEX5), .Hex4(HEX4), .Hex3(HEX3), .Hex2(HEX2), .Hex1(HEX1), .Hex0(HEX0));
									
	debounce 		db1 	(.clk(MAX10_CLK1_50), .button(KEY[1]), .pressed(b1p));
	debounce 		db0 	(.clk(MAX10_CLK1_50), .button(KEY[0]), .pressed(b0p));

endmodule


